#!/bin/bash

function bannerColor(){
    case ${2} in
    black)
        color=0
        ;;
    red)
        color=1
        ;;
    green)
        color=2
        ;;
    yellow)
        color=3
        ;;
    blue)
        color=4
        ;;
    magenta)
        color=5
        ;;
    cyan)
        color=6
        ;;
    white)
        color=7
        ;;
    *)
        echo "color is not set"
        exit 1
        ;;
    esac

    local msg="${3} ${1} ${3}"
    local edge=$(echo "${msg}" | sed "s/./${3}/g")
    tput setaf ${color}
    tput bold
    echo "${edge}"
    echo "${msg}"
    echo "${edge}"
    tput sgr 0
    echo
}
echo
bannerColor "StarStruck Init..." "yellow" "*"


if (source venv/bin/activate) ; then
	source venv/bin/activate
	bannerColor "Venv Activated..." "blue" "*"

else 
	cd python
	python -m venv venv 
	source venv/bin/activate
	pip install -r requirements.txt
	cd ..
	bannerColor "Venv Activated..." "blue" "*"
fi

bannerColor "Starting Web Server" "green" "*"

gunicorn app:app
